# Permalinks
permalink:           pretty

# Setup
title:               Harmeet's GitHub Blog
tagline:             Data Science Blog
url:                 http://harm8717.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Harmeet Hora
  url:               
  email:             harmeethora@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/harm8717

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
